permalink: pretty
markdown: kramdown
include:
  - _pages
  - _pages-jp
exclude:
  - ".rvmrc"
  - ".rbenv-version"
  - ".ruby-version"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Rakefile"
url : http://railsgirls.jp
defaults:
  -
    scope:
      path: ""
    values:
      hidden: true
  -
    scope:
      path: "_posts/blog"
    values:
      hidden: false
      image: /images/railsgirls-sq.png
plugins:
  - jekyll-paginate
paginate_path: "/blog/:num"
paginate: 15
